# -*- coding: utf-8 -*-
"""protium_project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkDrMhpQ-tJPG7H9qVSWotcTfeMMjVn-

# New Section
"""



"""# 1) What percentage of trades are with 30+ DPD (more than 30 days past due) among all the trades available?"""



import pandas as pd
import re
df1 = pd.read_xml("/content/customer1113697_loan1115483_crif_report.html.xml",xpath="//LOAN-DETAILS")
df2 = pd.read_xml("/content/customer1129550_loan1131339_crif_report.html.xml",xpath="//LOAN-DETAILS")
df3 = pd.read_xml("/content/customer1195586_loan1197471_crif_report.html.xml",xpath="//LOAN-DETAILS")
df4 = pd.read_xml("/content/customer14235_loan14235_crif_report.html.xml",xpath="//LOAN-DETAILS")
df5 = pd.read_xml("/content/customer16475_loan16475_crif_report.html.xml",xpath="//LOAN-DETAILS")
df6 = pd.read_xml("/content/customer40409_loan40409_crif_report.html.xml",xpath="//LOAN-DETAILS")
df7 = pd.read_xml("/content/customer773504_loan774538_crif_report.html.xml",xpath="//LOAN-DETAILS")
df8 = pd.read_xml("/content/customer787561_loan788638_crif_report.html.xml",xpath="//LOAN-DETAILS")
df9 = pd.read_xml("/content/customer794397_loan795497_crif_report.html.xml",xpath="//LOAN-DETAILS")
df10 = pd.read_xml("/content/customer898231_loan899591_crif_report.html.xml",xpath="//LOAN-DETAILS")
# cph_list = [df1["COMBINED-PAYMENT-HISTORY"],
#             df2["COMBINED-PAYMENT-HISTORY"],
#             df3["COMBINED-PAYMENT-HISTORY"],
#             df4["COMBINED-PAYMENT-HISTORY"],
#             df5["COMBINED-PAYMENT-HISTORY"],
#             df6["COMBINED-PAYMENT-HISTORY"],
#             df7["COMBINED-PAYMENT-HISTORY"],
#             df8["COMBINED-PAYMENT-HISTORY"],
#             df9["COMBINED-PAYMENT-HISTORY"],
#             df10["COMBINED-PAYMENT-HISTORY"]]
cph_list = [df1["COMBINED-PAYMENT-HISTORY"],df2["COMBINED-PAYMENT-HISTORY"],df3["COMBINED-PAYMENT-HISTORY"],df4["COMBINED-PAYMENT-HISTORY"],df5["COMBINED-PAYMENT-HISTORY"],df6["COMBINED-PAYMENT-HISTORY"],df7,df8["COMBINED-PAYMENT-HISTORY"],df9["COMBINED-PAYMENT-HISTORY"],df10["COMBINED-PAYMENT-HISTORY"]]
def count_30plusDPD(cph_list):
    pat = r',[1-9][0-9][0-9]/|,[0-9][3-9][0-9]'
    cl = []

    for cph in cph_list:
        t = []
        for trade in cph:
            count = 0
            for emi in range(0, len(trade)):
                match = re.search(pattern=pat, string=trade[emi])
                if match != None:
                    count = count+1
            t.append(count)
        cl.append(t)
    return cl
sl = count_30plusDPD(cph_list)
for i in sl:
  print("customer 1 loan percentage :",sl[0])
  print("customer 2 loan percentage :",sl[1])
  print("customer 3 loan percentage :",sl[2])
  print("customer 4 loan percentage :",sl[3])
  print("customer 5 loan percentage :",sl[4])
  print("customer 6 loan percentage :",sl[5])
  print("customer 7 loan percentage :",sl[6])
  print("customer 8 loan percentage :",sl[7])
  print("customer 9 loan percentage :",sl[8])
  print("customer 10 loan percentage :",sl[9])
  break
print()
print("total customers : " ,len(sl))



"""# 2) What is the sum of total disbursed amount for all loans for each customer?

"""

import pandas as pd
df1 = pd.read_xml("/content/customer1113697_loan1115483_crif_report.html.xml",xpath="//LOAN-DETAILS")
df2 = pd.read_xml("/content/customer1129550_loan1131339_crif_report.html.xml",xpath="//LOAN-DETAILS")
df3 = pd.read_xml("/content/customer1195586_loan1197471_crif_report.html.xml",xpath="//LOAN-DETAILS")
df4 = pd.read_xml("/content/customer14235_loan14235_crif_report.html.xml",xpath="//LOAN-DETAILS")
df5 = pd.read_xml("/content/customer16475_loan16475_crif_report.html.xml",xpath="//LOAN-DETAILS")
df6 = pd.read_xml("/content/customer40409_loan40409_crif_report.html.xml",xpath="//LOAN-DETAILS")
df7 = pd.read_xml("/content/customer773504_loan774538_crif_report.html.xml",xpath="//LOAN-DETAILS")
df8 = pd.read_xml("/content/customer787561_loan788638_crif_report.html.xml",xpath="//LOAN-DETAILS")
df9 = pd.read_xml("/content/customer794397_loan795497_crif_report.html.xml",xpath="//LOAN-DETAILS")
df10 = pd.read_xml("/content/customer898231_loan899591_crif_report.html.xml",xpath="//LOAN-DETAILS")

l = [df1["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df2["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df3["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df4["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df5["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df6["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df7["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df8["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df9["DISBURSED-AMT"].str.replace(",","").fillna("0"),
     df10["DISBURSED-AMT"].str.replace(",","").fillna("0")]
l2=[]
for i in l:
  for j in i:
    l2.append(i)
    break
l3 = list(c[3])

customer1 = []
for a in l2[0]:
  customer1.append(eval(a))
print("The sum of customer 1 is : ",sum(customer))

customer = []
for a in l2[1]:
  customer.append(eval(a))
print("The sum of customer 2 is : ",sum(customer))

customer = []
for a in l2[2]:
  customer.append(eval(a))
print("The sum of customer 3 is : ",sum(customer))

customer = []
for a in l2[3]:
  customer.append(eval(a))
print("The sum of customer 4 is : ",sum(customer))

customer = []
for a in l2[4]:
  customer.append(eval(a))
print("The sum of customer 5 is : ",sum(customer))

customer = []
for a in l2[5]:
  customer.append(eval(a))
print("The sum of customer 6 is : ",sum(customer))

customer = []
for a in l2[6]:
  customer.append(eval(a))
print("The sum of customer 7 is : ",sum(customer))

customer = []
for a in l2[7]:
  customer.append(eval(a))
print("The sum of customer 8 is : ",sum(customer))

customer = []
for a in l2[8]:
  customer.append(eval(a))
print("The sum of customer 9 is : ",sum(customer))

customer = []
for a in l2[9]:
  customer.append(eval(a))
print("The sum of customer 10 is : ",sum(customer))

"""# 3) What is the maximum number of months of 30+ due per trade was there? e.g. for trade 1 there are 3 occurrences of 30+, for trade 2 there are 6 occurrences and for trade 3 there are 3 occurrences then the answer will be 6."""

import pandas as pd
df1 = pd.read_xml("/content/customer1113697_loan1115483_crif_report.html.xml",xpath="//LOAN-DETAILS")
df2 = pd.read_xml("/content/customer1129550_loan1131339_crif_report.html.xml",xpath="//LOAN-DETAILS")
df3 = pd.read_xml("/content/customer1195586_loan1197471_crif_report.html.xml",xpath="//LOAN-DETAILS")
df4 = pd.read_xml("/content/customer14235_loan14235_crif_report.html.xml",xpath="//LOAN-DETAILS")
df5 = pd.read_xml("/content/customer16475_loan16475_crif_report.html.xml",xpath="//LOAN-DETAILS")
df6 = pd.read_xml("/content/customer40409_loan40409_crif_report.html.xml",xpath="//LOAN-DETAILS")
df7 = pd.read_xml("/content/customer773504_loan774538_crif_report.html.xml",xpath="//LOAN-DETAILS")
df8 = pd.read_xml("/content/customer787561_loan788638_crif_report.html.xml",xpath="//LOAN-DETAILS")
df9 = pd.read_xml("/content/customer794397_loan795497_crif_report.html.xml",xpath="//LOAN-DETAILS")
df10 = pd.read_xml("/content/customer898231_loan899591_crif_report.html.xml",xpath="//LOAN-DETAILS")

l = [df1["COMBINED-PAYMENT-HISTORY"],df2["COMBINED-PAYMENT-HISTORY"],df3["COMBINED-PAYMENT-HISTORY"],df4["COMBINED-PAYMENT-HISTORY"],df5["COMBINED-PAYMENT-HISTORY"],df6["COMBINED-PAYMENT-HISTORY"],df7["COMBINED-PAYMENT-HISTORY"],df8["COMBINED-PAYMENT-HISTORY"],df9["COMBINED-PAYMENT-HISTORY"],df10["COMBINED-PAYMENT-HISTORY"]]


df1



















